export const MOCK_CARD_GAME = [
  { id: 1,  title: "Zenless Zone Zero",   discount: "ลด 14%",                 image: "/images/Card/Img - Zenless Zone Zero.png" },
  { id: 2,  title: "Genshin Impact",      discount: "ลด 14%",                 image: "/images/Card/Img - Genshin Impact.png" },
  { id: 3,  title: "Honkai Impact 3",     discount: "ลด 14%",                 image: "/images/Card/Img - Honkai Impact 3.png" },
  { id: 4,  title: "Honkai Star Rail",    discount: "ลด 14%",                 image: "/images/Card/Img - Honkai Star Rail (Global).png" },
  { id: 5,  title: "GeForce NOW -",       discount: "Ultimate",               image: "/images/Card/Img - GeForce NOW-Ultimate.png" },
  { id: 6,  title: "GeForce NOW",         discount: "",                       image: "/images/Card/Img - GeForce NOW.png" },

  { id: 7,  title: "Legends Of",          discount: "",                       image: "/images/Card/Img - Legends Of Mushroom Rush.png" },
  { id: 8,  title: "Love and",            discount: "",                       image: "/images/Card/Img - LOVE AND DEEPSPACE.png" },
  { id: 9,  title: "Blood Strike",        discount: "",                       image: "/images/Card/Img - Blood Strike.png" },
  { id: 10, title: "The Seven Dead",      discount: "กดเพื่อรับฟรี",           image: "/images/Card/Img - The Seven Deadly Sins IDLE Adventure.png" },
  { id: 11, title: "True 5G Super",       discount: "",                       image: "/images/Card/Img - true5G.png" },
  { id: 12, title: "Ragnarok Origin",     discount: "ลด 20%",                 image: "/images/Card/Img - Ragnarok Origin.png" },

  { id: 13, title: "YOU mini Prepai",     discount: "",                       image: "/images/Card/Img - YOU mini Prepaid (true).png" },
  { id: 14, title: "YOU mini Postpa",     discount: "",                       image: "/images/Card/Img - YOU mini Postpaid (true).png" },
  { id: 15, title: "YOU mini (dtac)",     discount: "",                       image: "/images/Card/Img - YOU mini (dtac).png" },
  { id: 16, title: "Nikke (dtac)",        discount: "",                       image: "/images/Card/Img - Nikke (dtac).png" },
  { id: 17, title: "FREEFIRE (dtac)",     discount: "",                       image: "/images/Card/Img - FREEFIRE (dtac).png" },
  { id: 18, title: "UP2U PUBG",           discount: "",                       image: "/images/Card/Img - UP2U PUBG Mobile (true).png" },

  { id: 19, title: "UP2U PUBG",           discount: "",                       image: "/images/Card/Img - UP2U PUBG Mobile.png" },
  { id: 20, title: "Dummyland",           discount: "New",                    image: "/images/Card/Img - dummyland.png" },
  { id: 21, title: "TOL Product",         discount: "",                       image: "/images/Card/Img - TOL Product.png" },
  { id: 22, title: "Teamfight Tactics",   discount: "ลด 7%",                  image: "/images/Card/Img - Teamfight Tactics.png" },
  { id: 23, title: "Eggy Party",          discount: "ลด 18%",                 image: "/images/Card/Img - Eggy Party.png" },
  { id: 24, title: "Harry Potter:",       discount: "ลด 18%",                 image: "/images/Card/Img - Harry Potter Magic Awakened.png" },

  { id: 25, title: "FC Mobile",           discount: "NEW",                    image: "/images/Card/Img - FIFA Mobile.png" },
  { id: 26, title: "Ace Racer",           discount: "",                       image: "/images/Card/Img - Ace Racer.png" },
  { id: 27, title: "Entropy 2099",        discount: "",                       image: "/images/Card/Img - Entropy 2099.png" },
  { id: 28, title: "League of Legends",   discount: "ใหม่ ลด 7%",             image: "/images/Card/Img - League of legends.png" },
  { id: 29, title: "Ragnarok Mobil",      discount: "VIP Premium",            image: "/images/Card/Img - Ragnarok Mobile Premium.png" },
  { id: 30, title: "MU Origin 3",         discount: "ลด 14%",                 image: "/images/Card/Img - MU Origin 3.png" },

  { id: 31, title: "Basketrio",           discount: "New",                    image: "/images/Card/Img - Basketrio.png" },
  { id: 32, title: "Gaming Nation",       discount: "เล่นฟรี 3 วัน",           image: "/images/Card/Img - Gaming Nation PLAY.png" },
  { id: 33, title: "Top Eleven",          discount: "",                       image: "/images/Card/Img - top eleven.png" },
  { id: 34, title: "ZEPETO",              discount: "",                       image: "/images/Card/Img - gaming nation zepeto.png" },
  { id: 35, title: "Sausage Man",         discount: "",                       image: "/images/Card/Img - sausage_man.png" },
  { id: 36, title: "Dark Nemesis",        discount: "",                       image: "/images/Card/Img - dark-nemesis.png" },

  { id: 37, title: "8 Ball pool",         discount: "",                       image: "/images/Card/Img - 8 Ball pool.png" },
  { id: 38, title: "League of",           discount: "ลด 7%",                  image: "/images/Card/Img - league-of-legends-wr.png" },
  { id: 39, title: "Ragnarok X: Nex",     discount: "ลด 12%",                 image: "/images/Card/Img - Ragnarok X Next Generation.png" },
  { id: 40, title: "Black Desert SEA",    discount: "ลด 18%",                 image: "/images/Card/Img - Black Desert SEA.png" },
  { id: 41, title: "Steam Wallet",        discount: "รับเพิ่ม 5%",            image: "/images/Card/Img - Steam Wallet Code (THB).png" },
  { id: 42, title: "EOS RED",             discount: "",                       image: "/images/Card/Img - EOS RED.png" },

  { id: 43, title: "World Of Tanks",      discount: "",                       image: "/images/Card/Img - World Of Tanks.png" },
  { id: 44, title: "Nintendo eShop",      discount: "รับเพิ่ม 5%",            image: "/images/Card/Img - Nintendo eShop Cards.png" },
  { id: 45, title: "Minecraft Voucher",   discount: "",                       image: "/images/Card/Img - Minecraft.png" },
  { id: 46, title: "Ragnarok M:",         discount: "ลด 18%",                 image: "/images/Card/Img - Ragnarok M Eternal Love.png" },
  { id: 47, title: "Mobile Legends",      discount: "",                       image: "/images/Card/Img - Mobile Legends Diamonds.png" },
  { id: 48, title: "Tales of Gaia",       discount: "",                       image: "/images/Card/Img - Tales of Gaia.png" },

  { id: 49, title: "MARVEL Super",        discount: "",                       image: "/images/Card/Img - Marvel Super War.png" },
  { id: 50, title: "Tom & Jerry:",        discount: "",                       image: "/images/Card/Img - Tom & Jerry Chase.png" },
  { id: 51, title: "Marvel Duel",         discount: "",                       image: "/images/Card/Img - Marvel Duel.png" },
  { id: 52, title: "Onmyoji Arena",       discount: "ลด 18%",                 image: "/images/Card/Img - Onmyoji Arena.png" },
  { id: 53, title: "One Punch Man",       discount: "",                       image: "/images/Card/Img - One Punch Man.png" },
  { id: 54, title: "Modern Combat 5",     discount: "",                       image: "/images/Card/Img - Modern Combat.png" },

  { id: 55, title: "Cooking",             discount: "",                       image: "/images/Card/Img - Cooking adventure.png" },
  { id: 56, title: "Asphalt 9",           discount: "",                       image: "/images/Card/Img - Asphalt 9.png" },
  { id: 57, title: "MU Origin 2",         discount: "",                       image: "/images/Card/Img - MU Origin 2.png" },
  { id: 58, title: "Lords Mobile",        discount: "",                       image: "/images/Card/Img - Lords Mobile.png" },
  { id: 59, title: "VALORANT",            discount: "ดีแทค ลด 5% ทรู ลด 7%",   image: "/images/Card/Img - valorant.png" },
  { id: 60, title: "Legends of",          discount: "",                       image: "/images/Card/Img - Legends of Runeterra.png" }
];
