export const MOCKUP_PROMOTION_CARD = [
  {
    id: 1,
    img: "/",
    date: "2015-09-25",
    label: "Special for you",
    title: "MOCKUP_01",
  },
  {
    id: 2,
    img: "/",
    date: "2015-09-25",
    label: "Special for you",
    title: "MOCKUP_02",
  },
  {
    id: 3,
    img: "/",
    date: "2015-09-25",
    label: "Special for you",
    title: "MOCKUP_03",
  },
  {
    id: 4,
    img: "/",
    date: "2015-09-25",
    label: "Special for you",
    title: "MOCKUP_04",
  },
  {
    id: 5,
    img: "/",
    date: "2015-09-25",
    label: "Special for you",
    title: "MOCKUP_05",
  },
  {
    id: 6,
    img: "/",
    date: "2015-09-25",
    label: "Special for you",
    title: "MOCKUP_06",
  },
];

export const MOCKUP_PROMOTION_BANNER = [
  {
    id: 1,
    title: "8.8 รับโค้ดคุ้ม เติมเกมง่าย",
    subtitle: "โปรแรงลด 12%",
    description: "เติมเมอร์กี้ และดี่แกค คุ้ม ในโลกเกมคุณเลย!",
    discount: "12%",
    paymentMethods: ["Pay via dtac", "Pay via True"],
    image: "/images/banner/bn-promo-1.png",
  },
  {
    id: 2,
    title: "VALORANT Championship",
    subtitle: "รางวัลรวม 50,000 บาท",
    description: "ร่วมแข่งขันทัวร์นาเมนต์ใหญ่ที่สุดแห่งปี",
    discount: "FREE",
    buttonText: "สมัครเลย",
    buttonSecondary: "ดูรายละเอียด",
    paymentMethods: ["ฟรี", "ไม่เสียเงิน"],
    image: "/images/banner/bn-promo-2.png",
  },
  {
    id: 3,
    title: "League of Legends Wild Rift",
    subtitle: "Skins ฟรี 7 วัน",
    description: "รับ Champion และ Skin ฟรี สำหรับผู้เล่นใหม่",
    discount: "FREE",
    buttonText: "รับเลย",
    buttonSecondary: "เงื่อนไข",
    paymentMethods: ["สำหรับสมาชิก", "ไม่ต้องจ่าย"],
    image: "/images/banner/bn-promo-3.png",
  },
  {
    id: 4,
    title: "Free Fire MAX",
    subtitle: "Diamond x2",
    description: "เติม Diamond ได้เพิ่มเป็น 2 เท่า วันนี้ - 15 ส.ค.",
    discount: "2X",
    buttonText: "เติมเลย",
    buttonSecondary: "ดูโปรโมชั่น",
    paymentMethods: ["TrueWallet", "AIS mPAY"],
    image: "/images/banner/bn-promo-4.png",
  },
  {
    id: 5,
    title: "Mobile Legends",
    subtitle: "Starlight Plus ลด 30%",
    description: "อัพเกรด Starlight Plus ในราคาพิเศษ",
    discount: "30%",
    buttonText: "อัพเกรด",
    buttonSecondary: "รายละเอียด",
    paymentMethods: ["ผ่อน 0%", "จ่ายเต็ม"],
    image: "/images/banner/bn-promo-5.png",
  },
  {
    id: 6,
    title: "ROV Mega Sale",
    subtitle: "Voucher ลด 25%",
    description: "ซื้อ Voucher ทุกประเภท ลดสูงสุด 25%",
    discount: "25%",
    buttonText: "ซื้อเลย",
    buttonSecondary: "ดูสินค้า",
    paymentMethods: ["บัตรเครดิต", "โมบายแบงก์กิ้ง"],
    image: "/images/banner/bn-promo-6.png",
  },
  {
    id: 7,
    title: "Honkai Impact 3rd",
    subtitle: "Crystal Pack โบนัส 50%",
    description: "ซื้อ Crystal รับโบนัสเพิ่ม 50% จำกัดเวลา",
    discount: "50%",
    buttonText: "ซื้อ Crystal",
    buttonSecondary: "ดูแพ็คเกจ",
    paymentMethods: ["Steam Wallet", "Google Play"],
    image: "/images/banner/bn-promo-7.png",
  },
  {
    id: 8,
    title: "Genshin Impact",
    subtitle: "Welkin Moon + BP Bundle",
    description: "ซื้อคู่ Blessing + Battle Pass ในราคาพิเศษ",
    discount: "15%",
    buttonText: "ซื้อ Bundle",
    buttonSecondary: "ดูข้อมูล",
    paymentMethods: ["miHoYo Account", "Third Party"],
    image: "/images/banner/bn-promo-8.png",
  },
  {
    id: 9,
    title: "PUBG Mobile",
    subtitle: "UC เติมคุ้ม แถม BP Card",
    description: "เติม UC รับ Battle Pass Card ฟรี มูลค่า 280 บาท",
    discount: "FREE BP",
    buttonText: "เติม UC",
    buttonSecondary: "ดู BP Card",
    paymentMethods: ["Line Pay", "ShopeePay"],
    image: "/images/banner/bn-promo-9.png",
  },
  {
    id: 10,
    title: "Call of Duty Mobile",
    subtitle: "CP แพ็ค ลด 40%",
    description: "ซื้อ COD Points รับส่วนลดสูงสุด 40%",
    discount: "40%",
    buttonText: "ซื้อ CP",
    buttonSecondary: "ดูแพ็คเกจ",
    paymentMethods: ["Google Play", "App Store"],
    image: "/images/banner/bn-promo-10.png",
  },
  {
    id: 11,
    title: "Clash Royale",
    subtitle: "Pass Royale + Gems Bundle",
    description: "ซื้อ Pass Royale พร้อม Gems โบนัส 200%",
    discount: "200%",
    buttonText: "ซื้อ Pass",
    buttonSecondary: "ดู Gems",
    paymentMethods: ["Supercell ID", "Credit Card"],
    image: "/images/banner/bn-promo-11.png",
  },
  {
    id: 12,
    title: "Ragnarok X",
    subtitle: "Big Cat Coin ใหม่มาแล้ว!",
    description: "เติม Big Cat Coin รับโบนัส 100% วันแรกเท่านั้น",
    discount: "100%",
    buttonText: "เติมเลย",
    buttonSecondary: "ดู Coin",
    paymentMethods: ["Gravity ID", "Steam"],
    image: "/images/banner/bn-promo-12.png",
  },
  {
    id: 13,
    title: "Roblox",
    subtitle: "Robux Sale สุดคุ้ม",
    description: "ซื้อ Robux รับโบนัสเพิ่ม 25% จำกัดเวลา 7 วัน",
    discount: "25%",
    buttonText: "ซื้อ Robux",
    buttonSecondary: "ดูโปรโมชั่น",
    paymentMethods: ["Roblox Card", "PayPal"],
    image: "/images/banner/bn-promo-3.png",
  },
  {
    id: 14,
    title: "Minecraft",
    subtitle: "Minecoins แพ็คใหม่",
    description: "ซื้อ Minecoins รับ Skin Pack ฟรี มูลค่า 150 บาท",
    discount: "FREE PACK",
    buttonText: "ซื้อ Coins",
    buttonSecondary: "ดู Skin Pack",
    paymentMethods: ["Microsoft", "Xbox Live"],
    image: "/images/banner/bn-promo-4.png",
  },
  {
    id: 15,
    title: "Garena Speed Drifters",
    subtitle: "Tokens ลด 35%",
    description: "เติม Speed Tokens ลด 35% สำหรับรถใหม่และอัพเกรด",
    discount: "35%",
    buttonText: "เติม Tokens",
    buttonSecondary: "ดูรถใหม่",
    paymentMethods: ["Garena Shell", "Bank Transfer"],
    image: "/images/banner/bn-promo-15.png",
  },
];
